RETRIEVAL_PROMPT = """Please retrieve the information required to produce a {} domain for a BioCompute Object (BCO). {}"""

USABILITY_DOMAIN_RETRIEVAL = """The Usability domain in a BCO is a plain language description of what was done in the project or paper workflow. The information should convey the purpose of the paper and is a high level representation of the project workflow towards its purpose, not the low level details of the research. The Usability domain information is likely to be in paper sections such as the abstract, background, summary, conclusions, or any section that describes the purpose and background of the project."""

IO_DOMAIN_RETRIEVAL = """The Input Output domain (or IO domain) represents the list of global input and output files created by the computational workflow. The input subdomain records the references and input files for the entire pipeline. The output subdomain records the references and outputs (including media types) for the entire pipeline. The io domain information is likely to be in paper sections such as the methods, methodologies, steps, etc. Any section that describes the project steps and their intermediate input and output contents. It is also likely that this data is contained in the documentation and markdown files in the github repository. If the github repository information is included, it is highly likely that the input and output files are located in the repository. Make sure any URLs to files in the repository are exact."""

DESCRIPTION_DOMAIN_RETRIEVAL = """The Description domain specifies structured fields for the description of external resources, the pipeline or workflow steps, and the relationship of I/O objects. The description domain information is likely to be contained in multiple sections of the paper. The keywords are likely in sections such as the keywords, abstract, background, summary, etc. The pipeline steps are likely to be in paper sections such as the methods, methodologies, steps, etc. Any section that describes the project's pipeline steps and the background on the data used. It is also likely that this data is contained in the documentation and markdown files in the github repository if provided."""

EXECUTION_DOMAIN_RETRIEVAL = """The Execution domain specifies information needed for deployment, software configuration, and running applications in a dependent environment. Everything that is needed for someone to set up their machine to run the workflow should be described here. The execution domain information is likely to be in paper sections such as prerequisites, setup, data, methods, methodologies, etc. Any section that describes the setup, prerequisites, or environment for the workflow. It is also likely that this data is contained in the documentation and markdown files in the github repository if provided."""

PARAMETRIC_DOMAIN_RETRIEVAL = """The Parametric domain represents a list of parameters customizing the computational flow which can affect the output of the calculations. These fields can be custom to each kind of analysis and are tied to a particular pipeline implementation. This domain as a whole is optional so if there is no information in the paper that fits this domain then you can indicate that to the user. The parametric domain is likely contained in the paper sections such as methods, methodologies, etc. Any section that describes the exact details of the implementation and execution of the workflow. It is also likely that this data is contained in the documentation and markdown files in the github repository if provided."""

ERROR_DOMAIN_RETRIEVAL = """The Error domain can be used to determine what range of input returns and outputs are within the tolerance level defined in this subdomain and therefore can be used to optimize the algorithm. It consists of two subdomains: empirical and algorithmic. The empirical error subdomain contains empirically determined values such as limits of detectability, false positives, false negatives, statistical confidence of outcomes, etc. The algorithmic subdomain is descriptive of errors that originate by the fuzziness of the algorithms. This domain as a whole is optional so if there is no information in the paper that fits this domain then you can indicate that to the user."""
